using System.Collections.Generic;
using System.Collections.Immutable;
using System.Globalization;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace RazorSlicesHtmx.Generators;

[Generator]
public sealed class GenerateHtmlNamesGenerator : IIncrementalGenerator
{
    private const string AttributeMetadataName = "RazorSlicesHtmx.HtmlNames.GenerateHtmlNamesAttribute";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(static postInitContext =>
        {
            postInitContext.AddSource("GenerateHtmlNamesAttribute.g.cs", SourceText.From("""
namespace RazorSlicesHtmx.HtmlNames;

[global::System.AttributeUsage(global::System.AttributeTargets.Class | global::System.AttributeTargets.Struct, AllowMultiple = false, Inherited = false)]
public sealed class GenerateHtmlNamesAttribute : global::System.Attribute
{
    public GenerateHtmlNamesAttribute(int maxDepth = 0)
    {
        MaxDepth = maxDepth < 0 ? 0 : maxDepth;
    }

    public int MaxDepth { get; }
}
""", Encoding.UTF8));
        });

        var targets = context.SyntaxProvider.ForAttributeWithMetadataName(
            AttributeMetadataName,
            static (node, _) => node is ClassDeclarationSyntax or RecordDeclarationSyntax or StructDeclarationSyntax,
            static (syntaxContext, _) =>
            {
                if (syntaxContext.TargetSymbol is not INamedTypeSymbol symbol)
                {
                    return null;
                }

                var attribute = syntaxContext.Attributes.FirstOrDefault(static a =>
                    a.AttributeClass?.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)
                        .Contains(AttributeMetadataName, StringComparison.Ordinal) == true);

                if (attribute is null)
                {
                    return null;
                }

                var maxDepth = 0;
                if (attribute.ConstructorArguments.Length > 0 && attribute.ConstructorArguments[0].Value is int value)
                {
                    maxDepth = value < 0 ? 0 : value;
                }

                return new TargetModel(symbol, maxDepth);
            })
            .Where(static model => model is not null)
            .Select(static (model, _) => model!);

        var combined = context.CompilationProvider.Combine(targets.Collect());

        context.RegisterSourceOutput(combined, static (sourceProductionContext, input) =>
        {
            var (compilation, models) = input;
            if (models.IsDefaultOrEmpty)
            {
                return;
            }

            var projectNamespace = compilation.AssemblyName ?? "Generated";

            foreach (var model in models.Distinct(TargetModelComparer.Instance))
            {
                EmitModel(sourceProductionContext, projectNamespace, model);
            }
        });
    }

    private static void EmitModel(SourceProductionContext context, string projectNamespace, TargetModel model)
    {
        var entries = CollectEntries(model.Symbol, model.MaxDepth);
        if (entries.Count == 0)
        {
            return;
        }

        var targetNamespace = BuildTargetNamespace(projectNamespace, model.Symbol.ContainingNamespace);
        var className = model.Symbol.Name + "Html";

        var source = new StringBuilder();
        source.AppendLine("// <auto-generated />");
        source.Append("namespace ").Append(targetNamespace).AppendLine(";");
        source.AppendLine();
        source.Append("public static class ").Append(className).AppendLine();
        source.AppendLine("{");

        foreach (var entry in entries)
        {
            source.Append("    private static class ").Append(entry.FieldClassName).Append("Values").AppendLine();
            source.AppendLine("    {");
            source.Append("        public const string Name = \"").Append(entry.Name).AppendLine("\";");
            source.Append("        public const string Path = \"").Append(entry.Path).AppendLine("\";");
            source.Append("        public const string Id = \"").Append(entry.Id).AppendLine("\";");
            source.AppendLine("    }");

            source.Append("    public readonly struct ").Append(entry.FieldClassName).Append("Accessor").AppendLine();
            source.AppendLine("    {");
            source.Append("        public string Name => ").Append(entry.FieldClassName).Append("Values.Name;").AppendLine();
            source.Append("        public string Path => ").Append(entry.FieldClassName).Append("Values.Path;").AppendLine();
            source.Append("        public string Id => ").Append(entry.FieldClassName).Append("Values.Id;").AppendLine();
            source.AppendLine("    }");

            source.Append("    public static ").Append(entry.FieldClassName).Append("Accessor ").Append(entry.FieldClassName).AppendLine(" => default;");
            source.AppendLine();
        }

        source.AppendLine("}");

        var hintName = BuildHintName(model.Symbol, className);
        context.AddSource(hintName, SourceText.From(source.ToString(), Encoding.UTF8));
    }

    private static List<PropertyEntry> CollectEntries(INamedTypeSymbol symbol, int maxDepth)
    {
        var entries = new List<PropertyEntry>();
        var visited = new HashSet<INamedTypeSymbol>(SymbolEqualityComparer.Default);

        Walk(symbol, maxDepth, new List<string>(), entries, visited);

        return entries;
    }

    private static void Walk(
        INamedTypeSymbol type,
        int remainingDepth,
        List<string> parentPath,
        List<PropertyEntry> entries,
        HashSet<INamedTypeSymbol> visited)
    {
        if (!visited.Add(type))
        {
            return;
        }

        foreach (var property in type.GetMembers().OfType<IPropertySymbol>())
        {
            if (property.IsStatic || property.DeclaredAccessibility != Accessibility.Public)
            {
                continue;
            }

            var path = new List<string>(parentPath) { property.Name };
            var pathValue = string.Join(".", path);
            var nameValue = property.Name;
            var fieldClassName = string.Join("_", path);
            var idValue = ToKebabCase(type.Name + "-" + pathValue);

            entries.Add(new PropertyEntry(fieldClassName, nameValue, pathValue, idValue));

            if (remainingDepth > 0 && property.Type is INamedTypeSymbol child && IsComplexType(child))
            {
                Walk(child, remainingDepth - 1, path, entries, visited);
            }
        }

        visited.Remove(type);
    }

    private static bool IsComplexType(INamedTypeSymbol type)
    {
        var current = UnwrapNullable(type);

        if (current.TypeKind == TypeKind.Enum)
        {
            return false;
        }

        if (current.SpecialType != SpecialType.None)
        {
            return false;
        }

        if (current.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat) == "global::System.String")
        {
            return false;
        }

        foreach (var i in current.AllInterfaces)
        {
            if (i.OriginalDefinition.SpecialType == SpecialType.System_Collections_IEnumerable)
            {
                return false;
            }

            if (i.OriginalDefinition.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat).StartsWith("global::System.Collections.Generic.IEnumerable<", StringComparison.Ordinal))
            {
                return false;
            }
        }

        return current.TypeKind == TypeKind.Class || current.TypeKind == TypeKind.Struct;
    }

    private static INamedTypeSymbol UnwrapNullable(INamedTypeSymbol type)
    {
        if (type.OriginalDefinition.SpecialType == SpecialType.System_Nullable_T && type.TypeArguments.Length == 1 && type.TypeArguments[0] is INamedTypeSymbol inner)
        {
            return inner;
        }

        return type;
    }

    private static string BuildTargetNamespace(string projectNamespace, INamespaceSymbol sourceNamespace)
    {
        var sourceValue = sourceNamespace.IsGlobalNamespace ? string.Empty : sourceNamespace.ToDisplayString();
        if (string.IsNullOrWhiteSpace(sourceValue))
        {
            return projectNamespace + ".HtmlNames";
        }

        return projectNamespace + ".HtmlNames." + sourceValue;
    }

    private static string BuildHintName(INamedTypeSymbol symbol, string className)
    {
        var ns = symbol.ContainingNamespace.IsGlobalNamespace
            ? "Global"
            : symbol.ContainingNamespace.ToDisplayString().Replace('.', '_');

        return ns + "_" + className + ".g.cs";
    }

    private static string ToKebabCase(string value)
    {
        if (string.IsNullOrEmpty(value))
        {
            return value;
        }

        var sb = new StringBuilder(value.Length + 8);
        var lastWasDash = false;

        foreach (var c in value)
        {
            if (char.IsLetterOrDigit(c))
            {
                var lower = char.ToLower(c, CultureInfo.InvariantCulture);
                if (char.IsUpper(c) && sb.Length > 0 && !lastWasDash)
                {
                    sb.Append('-');
                }

                sb.Append(lower);
                lastWasDash = false;
                continue;
            }

            if (!lastWasDash && sb.Length > 0)
            {
                sb.Append('-');
                lastWasDash = true;
            }
        }

        if (sb.Length > 0 && sb[sb.Length - 1] == '-')
        {
            sb.Length -= 1;
        }

        return sb.ToString();
    }

    private sealed class TargetModel
    {
        public TargetModel(INamedTypeSymbol symbol, int maxDepth)
        {
            Symbol = symbol;
            MaxDepth = maxDepth;
        }

        public INamedTypeSymbol Symbol { get; }

        public int MaxDepth { get; }
    }

    private sealed class PropertyEntry
    {
        public PropertyEntry(string fieldClassName, string name, string path, string id)
        {
            FieldClassName = fieldClassName;
            Name = name;
            Path = path;
            Id = id;
        }

        public string FieldClassName { get; }

        public string Name { get; }

        public string Path { get; }

        public string Id { get; }
    }

    private sealed class TargetModelComparer : IEqualityComparer<TargetModel>
    {
        public static readonly TargetModelComparer Instance = new();

        public bool Equals(TargetModel? x, TargetModel? y)
        {
            if (x is null || y is null)
            {
                return false;
            }

            return SymbolEqualityComparer.Default.Equals(x.Symbol, y.Symbol) && x.MaxDepth == y.MaxDepth;
        }

        public int GetHashCode(TargetModel obj)
        {
            unchecked
            {
                return (SymbolEqualityComparer.Default.GetHashCode(obj.Symbol) * 397) ^ obj.MaxDepth;
            }
        }
    }
}
